### ISSUE TITLE
KeyError when trying to read a named type

### ISSUE THREAD

**Issue by fpietka** [tebeka/fastavro#101]
Hi,

I am trying to use fastavro to read data created from MySQL binlogs. In the data, I have two similar keys `before` and `after`. Since their schema is the same, `after` type is a name (namespace + name, see [documentation about names](http://avro.apache.org/docs/1.8.1/spec.html#names)) from the `before` key.

The error I have is like this:

```
fastavro/reader.py", line 479, in read_data
    data = READERS[record_type](fo, writer_schema, reader_schema)
KeyError u'my_namespace.my_name'
```

Am I missing something or isn't this supported?

Thanks in advance for your help.

**Comment by scottbelden** [comment]
Can you paste the schema? Based on the error, it sounds like your schema definition is something like:

```
schema = {
    'name': 'foo',
    'namespace': 'bar',
    'type': 'my_namespace.my_name',  # <--- Do you have something like this?
    'fields': [ ... ],
}
```

Is this true?

Also, if you could post the avro file somewhere that might help.

Thanks!

**Comment by fpietka** [comment]
For the context, we're getting this schema from Debezium:

```
{
  "connect.version": 1,
  "name": "Envelope",
  "fields": [
    {
      "default": null,
      "type": [
        "null",
        {
          "namespace": "video.company.video",
          "type": "record",
          "connect.name": "video.company.video.Value",
          "fields": [
            {
              "type": "long",
              "name": "video_id"
            },
            {
              "type": "long",
              "name": "user_id"
            },
            {
              "type": "long",
              "name": "duration"
            },
            {
              "type": {
                "connect.version": 1,
                "type": "string",
                "connect.name": "io.debezium.time.ZonedTimestamp"
              },
              "name": "created"
            },
            {
              "type": {
                "connect.version": 1,
                "type": "string",
                "connect.name": "io.debezium.time.ZonedTimestamp"
              },
              "name": "modified"
            },
            {
              "default": null,
              "type": [
                "null",
                "string"
              ],
              "name": "language"
            },
            {
              "default": null,
              "type": [
                "null",
                "string"
              ],
              "name": "country"
            },
            {
              "type": {
                "connect.version": 1,
                "type": "string",
                "connect.name": "io.debezium.data.Enum",
                "connect.parameters": {
                  "allowed": "video,audio"
                }
              },
              "name": "media_type"
            },
            {
              "type": "string",
              "name": "format"
            },
            {
              "type": {
                "type": "int",
                "connect.type": "int16"
              },
              "name": "width"
            },
            {
              "type": {
                "type": "int",
                "connect.type": "int16"
              },
              "name": "height"
            },
            {
              "default": null,
              "type": [
                "null",
                "string"
              ],
              "name": "checksum"
            },
            {
              "type": {
                "type": "int",
                "connect.type": "int16"
              },
              "name": "status_moderated"
            },
            {
              "type": {
                "type": "int",
                "connect.type": "int16"
              },
              "name": "status_deleted"
            },
            {
              "type": {
                "type": "int",
                "connect.type": "int16"
              },
              "name": "status_published"
            },
            {
              "type": {
                "type": "int",
                "connect.type": "int16"
              },
              "name": "status_private"
            },
            {
              "type": {
                "type": "int",
                "connect.type": "int16"
              },
              "name": "status_personal"
            },
            {
              "type": {
                "type": "int",
                "connect.type": "int16"
              },
              "name": "status_explicit"
            },
            {
              "type": {
                "type": "int",
                "connect.type": "int16"
              },
              "name": "allow_comments"
            },
            {
              "type": {
                "type": "int",
                "connect.type": "int16"
              },
              "name": "status_error"
            },
            {
              "type": {
                "type": "int",
                "connect.type": "int16"
              },
              "name": "status_ready_web"
            },
            {
              "type": {
                "type": "int",
                "connect.type": "int16"
              },
              "name": "channel_id"
            },
            {
              "default": null,
              "type": [
                "null",
                {
                  "connect.version": 1,
                  "type": "string",
                  "connect.name": "io.debezium.data.Enum",
                  "connect.parameters": {
                    "allowed": "ugc,partner,verified-partner"
                  }
                }
              ],
              "name": "category"
            }
          ],
          "name": "Value"
        }
      ],
      "name": "before"
    },
    {
      "default": null,
      "type": [
        "null",
        "video.company.video.Value"
      ],
      "name": "after"
    },
    {
      "type": {
        "namespace": "io.debezium.connector.mysql",
        "type": "record",
        "connect.name": "io.debezium.connector.mysql.Source",
        "fields": [
          {
            "type": "string",
            "name": "name"
          },
          {
            "type": "long",
            "name": "server_id"
          },
          {
            "type": "long",
            "name": "ts_sec"
          },
          {
            "default": null,
            "type": [
              "null",
              "string"
            ],
            "name": "gtid"
          },
          {
            "type": "string",
            "name": "file"
          },
          {
            "type": "long",
            "name": "pos"
          },
          {
            "type": "int",
            "name": "row"
          },
          {
            "default": null,
            "type": [
              "null",
              "boolean"
            ],
            "name": "snapshot"
          },
          {
            "default": null,
            "type": [
              "null",
              "long"
            ],
            "name": "thread"
          },
          {
            "default": null,
            "type": [
              "null",
              "string"
            ],
            "name": "db"
          },
          {
            "default": null,
            "type": [
              "null",
              "string"
            ],
            "name": "table"
          }
        ],
        "name": "Source"
      },
      "name": "source"
    },
    {
      "type": "string",
      "name": "op"
    },
    {
      "default": null,
      "type": [
        "null",
        "long"
      ],
      "name": "ts_ms"
    }
  ],
  "namespace": "video.company.video",
  "connect.name": "video.company.video.Envelope",
  "type": "record"
}
```

**Comment by scottbelden** [comment]
Hmmm... I tried to simplify your schema to what I thought the issue would be, but I'm not getting the error you got. Can you post a script that will re-create the error?

Here's what I tried:
```python
from io import BytesIO
import json
import fastavro

s = '''{
  "connect.version": 1,
  "name": "Envelope",
  "fields": [
    {
      "default": null,
      "type": [
        "null",
        {
          "namespace": "video.company.video",
          "type": "record",
          "connect.name": "video.company.video.Value",
          "fields": [
            {
              "type": "long",
              "name": "video_id"
            }
          ],
          "name": "Value"
        }
      ],
      "name": "before"
    },
    {
      "default": null,
      "type": [
        "null",
        "video.company.video.Value"
      ],
      "name": "after"
    },
    {
      "type": "string",
      "name": "op"
    }
  ],
  "namespace": "video.company.video",
  "connect.name": "video.company.video.Envelope",
  "type": "record"
}'''

schema = json.loads(s)

records = [ 
    {'before': None, 'after': None, 'op': 'foo'},
    {'before': {'video_id': 123}, 'after': None, 'op': 'foo'},
    {'before': None, 'after': {'video_id': 124}, 'op': 'foo'},
    {'before': {'video_id': 234}, 'after': {'video_id': 345}, 'op': 'foo'},
]

print(records)
print("")

fo = BytesIO()
fastavro.writer(fo, schema, records)

fo.seek(0)
reader = fastavro.reader(fo)
for record in reader:
    print(record)
```

**Comment by fpietka** [comment]
I'll try to reproduce with a minimal example, hopefully today.

**Comment by fpietka** [comment]
Hmm, now I can't reproduce the first error anymore, but I have another. At least I had been able to reproduce.

Just so you know, I'm using confluent_kafka. It doesn't work quite like your example, but rather like this (see https://github.com/confluentinc/confluent-kafka-python/blob/master/confluent_kafka/avro/serializer/message_serializer.py#L173):

```python
fo.seek(0)
from fastavro.reader import read_data

foo = read_data(fo, schema)
```
Doing so with your example, I get the same error I now get with my data:

```
Traceback (most recent call last):
  File "/tmp/fastavro_error.py", line 351, in <module>
    foo = read_data(fo, schema)
  File "/Users/f.pietka/.pyenv/versions/test-avro-27/lib/python2.7/site-packages/fastavro/reader.py", line 476, in read_data
    data = READERS[record_type](fo, writer_schema, reader_schema)
  File "/Users/f.pietka/.pyenv/versions/test-avro-27/lib/python2.7/site-packages/fastavro/reader.py", line 405, in read_record
    record[field['name']] = read_data(fo, field['type'])
  File "/Users/f.pietka/.pyenv/versions/test-avro-27/lib/python2.7/site-packages/fastavro/reader.py", line 476, in read_data
    data = READERS[record_type](fo, writer_schema, reader_schema)
  File "/Users/f.pietka/.pyenv/versions/test-avro-27/lib/python2.7/site-packages/fastavro/reader.py", line 366, in read_union
    index = read_long(fo)
  File "/Users/f.pietka/.pyenv/versions/test-avro-27/lib/python2.7/site-packages/fastavro/reader.py", line 225, in read_long
    raise StopIteration
StopIteration
```

If there's something wrong with the usage of fastavro, I can patch confluent_kafka, and make a PR for them to fix.

In the meantime I'm trying to reproduce my first error. Since Kafka most likely compacted data, it has changed since yesterday.

**Comment by fpietka** [comment]
Here is a (zipped) real world example we have:
[toto.zip](https://github.com/tebeka/fastavro/files/1324104/toto.zip)

**Comment by scottbelden** [comment]
I'll try to take a look at the IndexError you are getting. That does seem strange.

**Comment by fpietka** [comment]
Just to keep you updated, I was tracing what `read_record()` get.
First I have a type record:
```
{u'connect.name': u'video.company.video.Envelope',
 u'connect.version': 1,
 u'fields': [{u'default': None,
              u'name': u'before',
              u'type': [u'null',
                        {u'connect.name': u'video.company.video.Value',
                         u'fields': [{u'name': u'video_id',
                                      u'type': u'long'}],
                         u'name': u'Value',
                         u'namespace': u'video.company.video',
                         u'type': u'record'}]},
             {u'default': None,
              u'name': u'after',
              u'type': [u'null', u'video.company.video.Value']},
             {u'name': u'op', u'type': u'string'}],
 u'name': u'Envelope',
 u'namespace': u'video.company.video',
 u'type': u'record'}
```
Then a union from:
```
 [u'null',
 {u'connect.name': u'video.company.video.Value',
  u'fields': [{u'name': u'video_id', u'type': u'long'}],
  u'name': u'Value',
  u'namespace': u'video.company.video',
  u'type': u'record'}]
```
But in `read_union()`, it calls `read_long()` which gives `49`, and it tries this index on the 2 elements list.

**Comment by scottbelden** [comment]
So the use of:

```python
fo.seek(0)
from fastavro.reader import read_data

foo = read_data(fo, schema)
```

Won't work because the file object has the header which hasn't been read (https://github.com/tebeka/fastavro/blob/master/fastavro/reader.py#L565) as well as some block information (https://github.com/tebeka/fastavro/blob/master/fastavro/reader.py#L533-L534). 

If I modify your additions to read those as well, it works:
```python
fo.seek(0)

from fastavro.reader import read_data, read_long
from fastavro.reader import HEADER_SCHEMA

read_data(fo, HEADER_SCHEMA)
read_long(fo, None)
read_long(fo, None)
foo = read_data(fo, schema)
```

If that project is really calling `read_data` before doing those things, then that probably isn't the right thing. It sounds like they try to read the first record to see if fastavro can do it, so maybe it should be something more like this:

```python
next(fastavro.reader(fo))
```

**Comment by fpietka** [comment]
From my current understanding, they use some kind of custom header that they parse before.

Now I try to compare this working case with what happen in this library.

**Comment by fpietka** [comment]
From the example file I gave you, and according to confluent_kafka, you need to seek to 5 before sending to read_data() to get the initial `KeyError` error I reported.

Right now I am trying to understand what is different from that point.

**Comment by scottbelden** [comment]
Ah, okay. So I was able to see the issue you are talking about. The step that is missing is the call to `acquaint_schema`. This is a function that processes the schema before deserialization is done. For simple schemas, this function won't really do much and so there are probably times where you can call `read_data` directly and it will still work. However, for complex schemas like the one you have, it needs this step.

The two solutions that should work are to either call `acquaint_schema` yourself before `read_data` or you could use the `schemaless_reader` (since if you've skipped past the header, that's essentially what you have: https://github.com/tebeka/fastavro/blob/master/fastavro/reader.py#L596-L607)

The following code worked for me using your example:

```python
from io import BytesIO
from fastavro.reader import schemaless_reader, READERS, read_data
from fastavro.schema import acquaint_schema

new_schema = {u'connect.name': u'video.company.video.Envelope',
 u'connect.version': 1,
 u'fields': [{u'default': None,
              u'name': u'before',
              u'type': [u'null',
                        {u'connect.name': u'video.company.video.Value',
                         u'fields': [{u'name': u'video_id',
                                      u'type': u'long'}],
                         u'name': u'Value',
                         u'namespace': u'video.company.video',
                         u'type': u'record'}]},
             {u'default': None,
              u'name': u'after',
              u'type': [u'null', u'video.company.video.Value']},
             {u'name': u'op', u'type': u'string'}],
 u'name': u'Envelope',
 u'namespace': u'video.company.video',
 u'type': u'record'}

with open('../../Downloads/tmp/toto.avro', 'rb') as f:
  data = BytesIO(f.read())

# Solution 1
data.seek(5)
acquaint_schema(new_schema)
foo = read_data(data, new_schema)
print(foo)

# Solution 2
data.seek(5)
foo = schemaless_reader(data, new_schema)
print(foo)
```

**Comment by fpietka** [comment]
I works like a charm, thanks!

@scottbelden thanks again for sorting that out with me.

**Comment by scottbelden** [comment]
@fpietka I also wanted to note that the `schemaless_reader` (and it's partner the `schemaless_writer`) are only designed to handle a file object with a single record. If the stream/file object has multiple records then this approach won't work.
