### ISSUE TITLE
How to append records one by one?

### ISSUE THREAD

**Issue by hudvin** [tebeka/fastavro#12]
Hello,
As example you have something like 

records = [
{u'station': u'011990-99999', u'temp': 0, u'time': 1433269388},
{u'station': u'011990-99999', u'temp': 22, u'time': 1433270389},
{u'station': u'011990-99999', u'temp': -11, u'time': 1433273379},
{u'station': u'012650-99999', u'temp': 111, u'time': 1433275478},
]

with open('weather.avro', 'wb') as out:
writer(out, schema, records)

First of all, it's impossible to call last line more one one time - I get 

Exception in thread "main" org.apache.avro.AvroRuntimeException: java.io.IOException: Invalid sync!
	at org.apache.avro.file.DataFileStream.hasNext(DataFileStream.java:210)
	at org.apache.avro.tool.DataFileReadTool.run(DataFileReadTool.java:77)
	at org.apache.avro.tool.Main.run(Main.java:84)
	at org.apache.avro.tool.Main.main(Main.java:73)
Caused by: java.io.IOException: Invalid sync!
	at org.apache.avro.file.DataFileStream.nextRawBlock(DataFileStream.java:293)
	at org.apache.avro.file.DataFileStream.hasNext(DataFileStream.java:198)
	... 3 more

in  avro tools. And next  -I can't see any way to write records one by one (like writer(out, schema, record) or writer.write(out, schema, record)).

Vadym

**Comment by tebeka** [comment]
Thanks for reporting!

Currently `fastavro` supports only "one shot" writes. However `records` can be any iterable, including a generator the creates records one by one. I'll look into appending.

**Comment by hudvin** [comment]
Thank you for information!

**Comment by ekzhu** [comment]
Is appending possible now?

**Comment by scottbelden** [comment]
Yes, that should be possible. There is an example near the bottom of the documentation here: https://fastavro.readthedocs.io/en/latest/writer.html#fastavro-write

**Comment by ekzhu** [comment]
Thanks for your response!
