### ISSUE TITLE
fastavro(1) - Non-pretty failed due to indent=None

### ISSUE THREAD

**Issue by pyk** [tebeka/fastavro#148]
I have an avro writer in `python3.6` like the following:

```python
from fastavro import writer

def main():
    output = "samples.snappy.avro"
    out = open(output, "wb")
    schema = {
        "doc": "test",
        "name": "Record",
        "namespace": "collection",
        "type": "record",
        "fields": [
            {"name": "key", "type": ["string", "null"]}
        ]
    }
    records = [
        {"key": None},
        {"key": "value"}
    ]
    writer(out, schema, records, codec="snappy")
    out.close()
    print("Generated: {}".format(output))

if __name__ == "__main__":
    main()

```

When I try to dump the generated avro file, it raise an error like the following:

```text
% fastavro samples.snappy.avro 
Traceback (most recent call last):
  File "/home/pyk/.virtualenvs/x/bin/fastavro", line 11, in <module>
    sys.exit(main())
  File "/home/pyk/.virtualenvs/x/lib/python3.6/site-packages/fastavro/__main__.py", line 77, in main
    json_dump(record, indent)
  File "/home/pyk/.virtualenvs/x/lib/python3.6/site-packages/fastavro/six.py", line 33, in py3_json_dump
    json.dump(obj, stdout, indent=indent)
TypeError: an integer is required (got type NoneType)
```

But when I use `--pretty`, it runs as expected:

```
% fastavro -p samples.snappy.avro 
{
    "key":null
}
{
    "key":"value"
}
```

I think the problem is on this line https://github.com/tebeka/fastavro/blob/master/fastavro/__main__.py#L73

**Comment by pyk** [comment]
Oh yeah, I got this issue when listing a supported codecs

```
% fastavro --codecs
Traceback (most recent call last):
  File "/home/pyk/.virtualenvs/x/bin/fastavro", line 11, in <module>
    sys.exit(main())
  File "/home/pyk/.virtualenvs/x/lib/python3.6/site-packages/fastavro/__main__.py", line 50, in main
    print('\n'.join(sorted(avro._reader.BLOCK_READERS)))
AttributeError: module 'fastavro' has no attribute '_reader'

```

**Comment by scottbelden** [comment]
Thanks for the reports. https://github.com/tebeka/fastavro/pull/149 should resolve both of these issues and add some testing that wasn't being done.
