### ISSUE TITLE
decoding with compatible schema crashes with exception

### ISSUE THREAD

**Issue by abrarsheikh** [tebeka/fastavro#176]
There appears to be a bug in the decoding logic when the reader schema is different from writer schema

**writer_schema**
```
    {
        'name': 'name1',
        'type': 'record',
        'namespace': 'namespace1',
        'fields': [{
            'doc': 'test',
            'type': 'int',
            'default': 1,
            'name': 'good_field'
        }], 
        'doc': 'test'
    }
```

**reader_schema**
```
    {
        'name': 'name1',
        'doc': 'test',
        'namespace': 'namespace1',
        'fields': [{
            'name': 'good_field',
            'doc': 'test',
            'default': 1,
            'type': 'int'
        }, {
            'name': 'good_compatible_field',
            'doc': 'test',
            'default': 1,
            'type': 'int'
        }],
        'type': 'record'
    }
```

when i try to use the `reader_schema` to decode the encoded_data with `writer_schema` i get following exception
```
Traceback (most recent call last):
  File "fast_avro_bug.py", line 40, in <module>
    'type': 'record'
  File "fastavro/_read.pyx", line 690, in fastavro._read.schemaless_reader
  File "fastavro/_read.pyx", line 692, in fastavro._read.schemaless_reader
  File "fastavro/_read.pyx", line 524, in fastavro._read.read_data
  File "fastavro/_read.pyx", line 536, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 432, in fastavro._read.read_record
  File "fastavro/_read.pyx", line 454, in fastavro._read.read_record
  File "fastavro/_read.pyx", line 536, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 216, in fastavro._read.read_long
  File "fastavro/_read.pyx", line 228, in fastavro._read.read_long
StopIteration
```

as per the avro spec those 2 schemas should be compatible as the field `good_compatible_field` has a `default` value of `1`.

**sample code**
```
import fastavro
from six import BytesIO

stringio = BytesIO()
fastavro.schemaless_writer(
    stringio,
    {
        'name': 'name1',
        'type': 'record',
        'namespace': 'namespace1',
        'fields': [{
            'doc': 'test',
            'type': 'int',
            'default': 1,
            'name': 'good_field'
        }], 
        'doc': 'test'
    },
    {'good_field': 1}
)
encoded_data = stringio.getvalue()

actual_data = fastavro.schemaless_reader(
    BytesIO(encoded_data),
    {
        'name': 'name1',
        'doc': 'test',
        'namespace': 'namespace1',
        'fields': [{
            'name': 'good_field',
            'doc': 'test',
            'default': 1,
            'type': 'int'
        }, {
            'name': 'good_compatible_field',
            'doc': 'test',
            'default': 1,
            'type': 'int'
        }],
        'type': 'record'
    }
)

assert actual_data == {'good_field': 1, 'good_compatible_field': 1}
```

In the above snippet if you swap `reader_schema` and `writer_schema` the code seems to work as expected.

**Comment by scottbelden** [comment]
Thanks for the report. FWIW, this only affects the `schemaless_reader/writer`. At least one of the problems appears to be that we don't handle default values in the case of the schemaless reader. I think this is because I imagined that the same schema would be used for both. However, I think it makes sense that it should be able to handle the default values in the case like this. Of course, it definitely wouldn't be able to handle schema evolution.

I'll try to see if there is a nice way to handle the default values case.
